import {
  ClinicTenant,
  Doctor,
  Treatment,
  AIEmployee,
  PatientCRMRecord,
  Appointment,
  SmartQRCode,
  KnowledgeDocument,
  WorkflowAutomation,
  ReviewFeedback,
  PaymentTransaction,
  EmergencyTriageCase,
  AuditLog,
  QuickWinStats,
} from "@/types";

export const initialClinics: ClinicTenant[] = [
  {
    id: "clinic-in-01",
    name: "Apex Dental Studio & Implant Centre",
    tagline: "Advanced Aesthetics & Implantology",
    slug: "apex-dental",
    logoUrl: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=150&auto=format&fit=crop&q=80",
    brandColor: "#0d9488", // dental teal
    region: "IN",
    address: "Suite 402, Signature Towers, Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    website: "https://apexdentalstudio.in",
    locationsCount: 2,
    timeZone: "Asia/Kolkata",
    currency: "INR",
    phone: "+91 98201 44556",
    whatsappNumber: "+91 98201 44556",
    connectedCalendar: "google",
    complianceMode: "india_gst",
    gstNumber: "27AABCA1234F1Z8",
    rating: 4.9,
    reviewCount: 342,
    googlePlaceId: "ChIJb7c1234Apex",
    onboardingCompleted: true,
    createdAt: "2024-01-15T09:00:00Z",
  },
  {
    id: "clinic-us-02",
    name: "Beacon Hill Premier Dental",
    tagline: "Comprehensive Family & Cosmetic Dentistry",
    slug: "beacon-hill-dental",
    logoUrl: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=150&auto=format&fit=crop&q=80",
    brandColor: "#4f46e5", // brand indigo
    region: "US",
    address: "140 Charles Street, Suite 3B",
    city: "Boston",
    state: "MA",
    website: "https://beaconhilldental.com",
    locationsCount: 3,
    timeZone: "America/New_York",
    currency: "USD",
    phone: "+1 (617) 555-0198",
    whatsappNumber: "+1 (617) 555-0198",
    connectedCalendar: "outlook",
    complianceMode: "hipaa",
    npiNumber: "1982736450",
    rating: 4.95,
    reviewCount: 520,
    googlePlaceId: "ChIJc8d9876Beacon",
    onboardingCompleted: true,
    createdAt: "2024-02-01T10:30:00Z",
  },
];

export const initialDoctors: Doctor[] = [
  {
    id: "doc-1",
    clinicId: "clinic-in-01",
    name: "Dr. Rajesh Sharma, MDS",
    title: "Chief Prosthodontist & Implantologist",
    specialization: "Dental Implants & Full Mouth Rehab",
    availability: ["Monday", "Tuesday", "Wednesday", "Friday", "Saturday"],
    appointmentDurationMinutes: 45,
    avatarUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=120&auto=format&fit=crop&q=80",
    bio: "Over 16 years of clinical excellence in computer-guided surgical dental implants and cosmetic rehabilitation.",
    active: true,
  },
  {
    id: "doc-2",
    clinicId: "clinic-in-01",
    name: "Dr. Ananya Sen, MDS",
    title: "Senior Orthodontist & Clear Aligner Specialist",
    specialization: "Invisalign, Clear Aligners & Braces",
    availability: ["Tuesday", "Thursday", "Saturday", "Sunday"],
    appointmentDurationMinutes: 30,
    avatarUrl: "https://images.unsplash.com/photo-1594824813636-25807952951b?w=120&auto=format&fit=crop&q=80",
    bio: "Certified Diamond Plus Invisalign Provider with 1,200+ smile transformations completed.",
    active: true,
  },
  {
    id: "doc-3",
    clinicId: "clinic-us-02",
    name: "Dr. Emily Vance, DDS, FAGD",
    title: "Lead Cosmetic & Restorative Dentist",
    specialization: "Veneers, Smile Design & Crowns",
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday"],
    appointmentDurationMinutes: 45,
    avatarUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=120&auto=format&fit=crop&q=80",
    bio: "Graduate of Harvard School of Dental Medicine, Fellow of the Academy of General Dentistry.",
    active: true,
  },
  {
    id: "doc-4",
    clinicId: "clinic-us-02",
    name: "Dr. Michael Chang, DMD",
    title: "Periodontist & Implant Surgeon",
    specialization: "Implants, Bone Grafting & Laser Periodontics",
    availability: ["Wednesday", "Thursday", "Friday", "Saturday"],
    appointmentDurationMinutes: 60,
    avatarUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=120&auto=format&fit=crop&q=80",
    bio: "Board-certified periodontist specializing in minimally invasive microsurgery and immediate-load implants.",
    active: true,
  },
];

export const initialTreatments: Treatment[] = [
  {
    id: "treat-1",
    clinicId: "clinic-in-01",
    name: "Dental Cleaning & Ultrasonic Scaling",
    category: "Preventive",
    priceINR: 2000,
    priceUSD: 120,
    insuranceCovered: true,
    durationMinutes: 30,
    description: "Deep ultrasonic scaling, air polishing, stain removal, and fluoridation.",
    acceptanceRate: 92,
  },
  {
    id: "treat-2",
    clinicId: "clinic-in-01",
    name: "Single Tooth Dental Implant (Titanium/Zirconia)",
    category: "Surgical",
    priceINR: 38000,
    priceUSD: 1850,
    insuranceCovered: false,
    durationMinutes: 60,
    description: "3D CBCT guided surgical implant placement with custom abutment and lifetime warranty.",
    acceptanceRate: 74,
  },
  {
    id: "treat-3",
    clinicId: "clinic-in-01",
    name: "Invisalign Clear Aligners (Full Arch)",
    category: "Orthodontics",
    priceINR: 125000,
    priceUSD: 4200,
    insuranceCovered: true,
    durationMinutes: 45,
    description: "Custom digital 3D iTero scan with predictive smile simulation and full aligner set.",
    acceptanceRate: 68,
  },
  {
    id: "treat-4",
    clinicId: "clinic-in-01",
    name: "Single-Sitting Rotary Root Canal (RCT)",
    category: "Endodontics",
    priceINR: 6500,
    priceUSD: 750,
    insuranceCovered: true,
    durationMinutes: 45,
    description: "Microscopic painless rotary RCT with bioceramic sealer and post-core restoration.",
    acceptanceRate: 88,
  },
  {
    id: "treat-5",
    clinicId: "clinic-in-01",
    name: "Porcelain Ceramic Veneers (Per Tooth)",
    category: "Cosmetic",
    priceINR: 15000,
    priceUSD: 1100,
    insuranceCovered: false,
    durationMinutes: 45,
    description: "Ultra-thin custom layered E-max porcelain veneers for aesthetic smile harmony.",
    acceptanceRate: 65,
  },
  {
    id: "treat-6",
    clinicId: "clinic-in-01",
    name: "CAD/CAM Zirconia Crown",
    category: "Restorative",
    priceINR: 11000,
    priceUSD: 950,
    insuranceCovered: true,
    durationMinutes: 40,
    description: "Monolithic high-translucency multilayer zirconia crown with 15-year warranty.",
    acceptanceRate: 85,
  },
  {
    id: "treat-7",
    clinicId: "clinic-in-01",
    name: "Laser Teeth Whitening (Zoom 4)",
    category: "Cosmetic",
    priceINR: 9500,
    priceUSD: 450,
    insuranceCovered: false,
    durationMinutes: 45,
    description: "Philips Zoom Whitespeed in-office power whitening lifting up to 8 shades in 45 mins.",
    acceptanceRate: 79,
  },
];

export const initialAIEmployees: AIEmployee[] = [
  {
    id: "emp-1",
    clinicId: "clinic-in-01",
    persona: "receptionist",
    name: "Aria",
    roleTitle: "AI Dental Front Desk Receptionist",
    status: "active",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80",
    temperature: 0.2,
    prompt:
      "You are Aria, the 24x7 intelligent front desk receptionist for Apex Dental Studio. You warmly greet patients, answer questions on clinic timings, directions, pricing ranges, and doctor availability. You triage urgent issues and smoothly guide patients through scheduling appointments on WhatsApp or web chat. If a patient is anxious, reassure them gently.",
    confidenceThreshold: 0.85,
    workingHours: "24/7 Uninterrupted",
    escalationRules: "Escalate immediately on severe pain (8/10+), facial trauma, uncontrolled bleeding, or explicit request for Human Front Desk.",
    toneOfVoice: "Warm & Empathetic",
    conversationsHandled: 1420,
    resolutionRate: 94.2,
    keyResponsibilities: [
      "24/7 WhatsApp & Web Appointment Booking",
      "Instant FAQ, Timing & Location Guidance",
      "Dynamic Doctor Calendar Sync",
      "Emergency Triage Escalation",
      "Automated Front Desk Offload",
    ],
  },
  {
    id: "emp-2",
    clinicId: "clinic-in-01",
    persona: "treatment_coordinator",
    name: "Vikram",
    roleTitle: "AI High-Value Treatment Coordinator",
    status: "active",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    temperature: 0.3,
    prompt:
      "You are Vikram, the AI Treatment Coordinator specializing in high-value elective procedures: Dental Implants, Invisalign, Veneers, and Smile Makeovers. You help patients understand procedure benefits, longevity, pain-free protocols, and EMI/Financing options without sounding pushy. You compute Treatment Acceptance Scores based on patient engagement.",
    confidenceThreshold: 0.88,
    workingHours: "8:00 AM - 10:00 PM Daily",
    escalationRules: "Hand over to Senior Treatment Coordinator when patient asks for customized package discounts or complex clinical staging.",
    toneOfVoice: "Professional & Direct",
    conversationsHandled: 648,
    resolutionRate: 88.5,
    keyResponsibilities: [
      "Implants & Invisalign Nurturing",
      "EMI & Flexible Financing Explanations",
      "Predictive Acceptance Scoring (0-100)",
      "Automated Multi-Touch Follow-Up Sequences",
      "Before & After Case Education",
    ],
  },
  {
    id: "emp-3",
    clinicId: "clinic-in-01",
    persona: "recall_manager",
    name: "Tara",
    roleTitle: "AI Patient Recall & Retention Manager",
    status: "active",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80",
    temperature: 0.2,
    prompt:
      "You are Tara, responsible for maximizing patient lifetime value through timely preventative recall. You monitor hygiene schedules (6-month cleanings, annual exams, aligner switch checkpoints). You send personalized WhatsApp reminder cards with 1-click confirmation and rescheduling buttons.",
    confidenceThreshold: 0.9,
    workingHours: "9:00 AM - 7:00 PM Weekdays",
    escalationRules: "Trigger human front desk task if patient fails to respond after 3 automated recall touches over 21 days.",
    toneOfVoice: "Warm & Empathetic",
    conversationsHandled: 2150,
    resolutionRate: 91.8,
    keyResponsibilities: [
      "6-Month Hygiene Recall Reminders",
      "Aligner / Braces Adjustment Scheduling",
      "1-Click WhatsApp Direct Rescheduling",
      "Patient Churn Prevention",
      "Post-Op Follow-Up Check-ins",
    ],
  },
  {
    id: "emp-4",
    clinicId: "clinic-in-01",
    persona: "insurance_coordinator",
    name: "Marcus",
    roleTitle: "AI Insurance & Verification Specialist",
    status: "active",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    temperature: 0.1,
    prompt:
      "You are Marcus, the AI Insurance Coordinator. For US clinics, you instantly intake policy details (Delta Dental, MetLife, Cigna, Aetna, Guardian, UnitedHealthcare), parse member IDs, compute co-pays, deductibles, and pre-authorization requirements. For India clinics, you clarify corporate cashless empanelment policies.",
    confidenceThreshold: 0.92,
    workingHours: "8:00 AM - 8:00 PM Daily",
    escalationRules: "Escalate to Billing Lead when out-of-network coverage dispute occurs or claim denial risk exceeds 30%.",
    toneOfVoice: "Concise & Reassuring",
    conversationsHandled: 890,
    resolutionRate: 93.4,
    keyResponsibilities: [
      "Real-time US Eligibility Verification",
      "Co-pay & Deductible Transparency",
      "Pre-Authorization Workflow Tracking",
      "Digital Card & Document Ingestion",
      "Out-of-pocket Estimator",
    ],
  },
  {
    id: "emp-5",
    clinicId: "clinic-in-01",
    persona: "billing_assistant",
    name: "Zara",
    roleTitle: "AI Billing & Collections Assistant",
    status: "active",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    temperature: 0.2,
    prompt:
      "You are Zara, the automated billing assistant. You dispatch instant payment links for advances, deposits, and outstanding co-pays. In India, you handle UPI QR, Razorpay, PhonePe, and GST invoices. In the US, you facilitate Stripe, ACH, and medical financing. You send polite, timely payment reminder sequences.",
    confidenceThreshold: 0.95,
    workingHours: "9:00 AM - 8:00 PM Daily",
    escalationRules: "Escalate to clinic manager if payment is overdue > 30 days or patient disputes invoice line items.",
    toneOfVoice: "Concise & Reassuring",
    conversationsHandled: 1240,
    resolutionRate: 96.1,
    keyResponsibilities: [
      "Instant Payment Links (UPI / Stripe)",
      "Automated Treatment Deposit Invoicing",
      "Gentle WhatsApp Overdue Follow-ups",
      "Zero-Interest EMI Plan Options",
      "GST & Superbill Generation",
    ],
  },
  {
    id: "emp-6",
    clinicId: "clinic-in-01",
    persona: "patient_care",
    name: "Chloe",
    roleTitle: "AI Patient Care & Post-Op Coordinator",
    status: "active",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    temperature: 0.25,
    prompt:
      "You are Chloe, dedicated to exceptional post-treatment patient recovery. Following extractions, implants, or root canals, you message patients at 2 hours, 24 hours, and 4 days post-op to check on bleeding, pain levels, and medication compliance. You provide instant dietary and ice-pack guidance.",
    confidenceThreshold: 0.89,
    workingHours: "24/7 Post-Op Monitoring",
    escalationRules: "Immediate emergency escalation to on-call surgeon if patient reports fever > 101F, uncontrollable bleeding, or severe swelling.",
    toneOfVoice: "Warm & Empathetic",
    conversationsHandled: 980,
    resolutionRate: 97.0,
    keyResponsibilities: [
      "Automated Day-1 & Day-3 Post-Op Check-ins",
      "Medication & Home Care Instructions",
      "Post-Op Pain Monitoring & Reassurance",
      "Emergency Complication Routing",
      "High-NPS Review Trigger Handover",
    ],
  },
];

export const initialCRMLeads: PatientCRMRecord[] = [
  {
    id: "lead-1",
    clinicId: "clinic-in-01",
    name: "Rohit Malhotra",
    phone: "+91 98200 11223",
    email: "rohit.m@gmail.com",
    dob: "1988-06-14",
    gender: "Male",
    status: "treatment_proposed",
    leadScore: 88,
    treatmentIntentScore: 92,
    treatmentInterest: "Single Tooth Dental Implant",
    estimatedValue: 38000,
    preferredDoctorId: "doc-1",
    lastContactDate: "2024-03-24T14:30:00Z",
    nextRecallDate: "2024-04-02",
    medicalAlerts: ["Mild Penicillin Allergy"],
    digitalIntakeCompleted: true,
    timeline: [
      {
        id: "t1",
        timestamp: "2024-03-20T10:15:00Z",
        actor: "Patient",
        action: "Scanned WhatsApp Connect QR on Google Ads",
      },
      {
        id: "t2",
        timestamp: "2024-03-20T10:16:00Z",
        actor: "AI Receptionist",
        action: "Aria qualified lead interest in molar implant & booked consultation with Dr. Rajesh Sharma",
      },
      {
        id: "t3",
        timestamp: "2024-03-22T11:00:00Z",
        actor: "Dentist",
        action: "Consultation & CBCT scan completed. Treatment plan #APX-491 presented.",
      },
      {
        id: "t4",
        timestamp: "2024-03-23T15:45:00Z",
        actor: "AI Coordinator",
        action: "Vikram sent 3D implant video & 3-month zero-interest EMI proposal via WhatsApp",
      },
    ],
  },
  {
    id: "lead-2",
    clinicId: "clinic-in-01",
    name: "Pooja Deshmukh",
    phone: "+91 97690 44552",
    email: "pooja.d@techcorp.in",
    dob: "1995-11-20",
    gender: "Female",
    status: "treatment_accepted",
    leadScore: 94,
    treatmentIntentScore: 96,
    treatmentInterest: "Invisalign Clear Aligners",
    estimatedValue: 125000,
    preferredDoctorId: "doc-2",
    lastContactDate: "2024-03-25T09:12:00Z",
    nextRecallDate: "2024-04-10",
    medicalAlerts: [],
    digitalIntakeCompleted: true,
    timeline: [
      {
        id: "t2-1",
        timestamp: "2024-03-15T12:00:00Z",
        actor: "AI Receptionist",
        action: "Answered aligner vs metal braces query on website chat",
      },
      {
        id: "t2-2",
        timestamp: "2024-03-18T16:30:00Z",
        actor: "Dentist",
        action: "iTero 3D digital smile simulation scan performed by Dr. Ananya Sen",
      },
      {
        id: "t2-3",
        timestamp: "2024-03-24T18:00:00Z",
        actor: "Patient",
        action: "Accepted Invisalign treatment plan & paid advance deposit via UPI QR",
      },
    ],
  },
  {
    id: "lead-3",
    clinicId: "clinic-in-01",
    name: "Amitabh Banerjee",
    phone: "+91 98110 33445",
    email: "a.banerjee@outlook.com",
    dob: "1972-04-05",
    gender: "Male",
    status: "in_progress",
    leadScore: 90,
    treatmentIntentScore: 90,
    treatmentInterest: "Rotary Root Canal + Zirconia Crown",
    estimatedValue: 17500,
    preferredDoctorId: "doc-1",
    lastContactDate: "2024-03-24T18:40:00Z",
    medicalAlerts: ["Type 2 Diabetes (Controlled)"],
    digitalIntakeCompleted: true,
    timeline: [
      {
        id: "t3-1",
        timestamp: "2024-03-21T08:10:00Z",
        actor: "AI Receptionist",
        action: "Emergency triage: severe night tooth pain (Urgency Score 8/10), booked same-day slot",
      },
      {
        id: "t3-2",
        timestamp: "2024-03-21T11:30:00Z",
        actor: "Dentist",
        action: "Completed Single-Sitting rotary endodontics. Canal obturated.",
      },
      {
        id: "t3-3",
        timestamp: "2024-03-22T09:00:00Z",
        actor: "AI Coordinator",
        action: "Chloe sent Day-1 post-op pain check: patient reported pain reduced to 2/10",
      },
    ],
  },
  {
    id: "lead-4",
    clinicId: "clinic-in-01",
    name: "Sunita Kapoor",
    phone: "+91 99300 77889",
    email: "sunita.kapoor@gmail.com",
    dob: "1982-08-12",
    gender: "Female",
    status: "new_lead",
    leadScore: 65,
    treatmentIntentScore: 55,
    treatmentInterest: "Teeth Whitening & Cleaning",
    estimatedValue: 11500,
    preferredDoctorId: "doc-2",
    lastContactDate: "2024-03-25T11:05:00Z",
    medicalAlerts: [],
    digitalIntakeCompleted: false,
    timeline: [
      {
        id: "t4-1",
        timestamp: "2024-03-25T11:05:00Z",
        actor: "Patient",
        action: "Scanned Universal Smart QR at front desk counter",
      },
      {
        id: "t4-2",
        timestamp: "2024-03-25T11:06:00Z",
        actor: "AI Receptionist",
        action: "Dispatched digital intake form & teeth whitening brochure via WhatsApp",
      },
    ],
  },
  {
    id: "lead-5",
    clinicId: "clinic-us-02",
    name: "Sarah Jenkins",
    phone: "+1 (617) 555-8921",
    email: "sjenkins@bostonbio.org",
    dob: "1991-03-15",
    gender: "Female",
    status: "consultation_scheduled",
    leadScore: 82,
    treatmentIntentScore: 85,
    treatmentInterest: "Porcelain Veneers (6 Upper)",
    estimatedValue: 6600,
    preferredDoctorId: "doc-3",
    lastContactDate: "2024-03-24T16:20:00Z",
    insuranceProvider: "Delta Dental Premier",
    insuranceMemberId: "DD-99281726",
    verificationStatus: "Verified",
    medicalAlerts: ["Latex Sensitivity"],
    digitalIntakeCompleted: true,
    timeline: [
      {
        id: "t5-1",
        timestamp: "2024-03-23T14:00:00Z",
        actor: "AI Receptionist",
        action: "Qualified aesthetic smile makeover inquiry from Instagram bio QR",
      },
      {
        id: "t5-2",
        timestamp: "2024-03-23T14:05:00Z",
        actor: "AI Coordinator",
        action: "Marcus verified Delta Dental benefits: $1,500 annual max applied to pre-op exam",
      },
    ],
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: "apt-1",
    clinicId: "clinic-in-01",
    patientId: "lead-1",
    patientName: "Rohit Malhotra",
    phone: "+91 98200 11223",
    doctorId: "doc-1",
    doctorName: "Dr. Rajesh Sharma",
    treatmentName: "Dental Implant Surgical Stage 1",
    dateTime: "2024-04-02T10:30:00Z",
    durationMinutes: 60,
    status: "confirmed",
    channel: "WhatsApp AI",
    notes: "Patient confirmed via WhatsApp 1-click button. CBCT reviewed.",
  },
  {
    id: "apt-2",
    clinicId: "clinic-in-01",
    patientId: "lead-2",
    patientName: "Pooja Deshmukh",
    phone: "+91 97690 44552",
    doctorId: "doc-2",
    doctorName: "Dr. Ananya Sen",
    treatmentName: "Invisalign Aligner Delivery & Attachment Placement",
    dateTime: "2024-04-10T14:00:00Z",
    durationMinutes: 45,
    status: "confirmed",
    channel: "WhatsApp AI",
  },
  {
    id: "apt-3",
    clinicId: "clinic-in-01",
    patientId: "lead-3",
    patientName: "Amitabh Banerjee",
    phone: "+91 98110 33445",
    doctorId: "doc-1",
    doctorName: "Dr. Rajesh Sharma",
    treatmentName: "CAD/CAM Zirconia Crown Bonding",
    dateTime: "2024-03-28T16:00:00Z",
    durationMinutes: 30,
    status: "reminded_24h",
    channel: "WhatsApp AI",
    notes: "24h reminder sent. Patient clicked 'Confirm'.",
  },
  {
    id: "apt-4",
    clinicId: "clinic-in-01",
    patientId: "lead-4",
    patientName: "Sunita Kapoor",
    phone: "+91 99300 77889",
    doctorId: "doc-2",
    doctorName: "Dr. Ananya Sen",
    treatmentName: "Dental Cleaning & Ultrasonic Scaling",
    dateTime: "2024-03-26T11:30:00Z",
    durationMinutes: 30,
    status: "pending",
    channel: "Smart QR",
  },
];

export const initialSmartQRs: SmartQRCode[] = [
  {
    id: "qr-1",
    clinicId: "clinic-in-01",
    type: "universal",
    title: "Universal Smart Clinic QR",
    subtitle: "One QR for Everything: Booking, WhatsApp, Payments & Reviews",
    targetUrl: "/portal/clinic-in-01/hub",
    scansCount: 1420,
    conversionsCount: 486,
    revenueGenerated: 840000,
    customStyles: {
      fgColor: "#0d9488",
      bgColor: "#ffffff",
      frameStyle: "poster",
      ctaText: "SCAN FOR APEX DENTAL HUB",
    },
    locationTag: "Main Entrance & Reception Desk",
  },
  {
    id: "qr-2",
    clinicId: "clinic-in-01",
    type: "whatsapp",
    title: "WhatsApp Connect QR",
    subtitle: "Scan to start 24x7 AI Dental Receptionist on WhatsApp",
    targetUrl: "https://wa.me/919820144556?text=Hi%20Apex%20Dental,%20I%20would%20like%20to%20book%20an%20appointment",
    scansCount: 940,
    conversionsCount: 412,
    revenueGenerated: 620000,
    customStyles: {
      fgColor: "#059669",
      bgColor: "#ffffff",
      frameStyle: "callout",
      ctaText: "CHAT WITH AI RECEPTIONIST ON WHATSAPP",
    },
    locationTag: "Outdoor Signboard & Business Cards",
  },
  {
    id: "qr-3",
    clinicId: "clinic-in-01",
    type: "review",
    title: "AI Google Review QR",
    subtitle: "Automated NPS review filter: 8-10 to Google, 1-7 to Private Clinic Care",
    targetUrl: "/portal/clinic-in-01/review",
    scansCount: 680,
    conversionsCount: 310,
    revenueGenerated: 0,
    customStyles: {
      fgColor: "#4f46e5",
      bgColor: "#ffffff",
      frameStyle: "badge",
      ctaText: "RATE YOUR 5-STAR VISIT",
    },
    locationTag: "Checkout Counter & Waiting Area",
  },
  {
    id: "qr-4",
    clinicId: "clinic-in-01",
    type: "payment",
    title: "Touchless Instant Payment QR",
    subtitle: "India UPI / Razorpay / US Stripe touchless payment stand",
    targetUrl: "/portal/clinic-in-01/pay",
    scansCount: 820,
    conversionsCount: 512,
    revenueGenerated: 1450000,
    customStyles: {
      fgColor: "#0f172a",
      bgColor: "#ffffff",
      frameStyle: "callout",
      ctaText: "SCAN TO PAY VIA UPI / CARD",
    },
    locationTag: "Front Desk Cashier & Operatory 1 & 2",
  },
  {
    id: "qr-5",
    clinicId: "clinic-in-01",
    type: "appointment",
    title: "Direct Doctor Booking QR",
    subtitle: "Scan to see open doctor slots and book in 30 seconds",
    targetUrl: "/portal/clinic-in-01/hub#booking",
    scansCount: 430,
    conversionsCount: 198,
    revenueGenerated: 310000,
    customStyles: {
      fgColor: "#0d9488",
      bgColor: "#ffffff",
      frameStyle: "simple",
      ctaText: "BOOK AN APPOINTMENT",
    },
    locationTag: "Elevator Lobby & Partner Pharmacy",
  },
  {
    id: "qr-6",
    clinicId: "clinic-in-01",
    type: "intake",
    title: "Paperless Patient Intake QR",
    subtitle: "Pre-appointment medical history, insurance & digital signature",
    targetUrl: "/portal/clinic-in-01/intake",
    scansCount: 510,
    conversionsCount: 460,
    revenueGenerated: 0,
    customStyles: {
      fgColor: "#0284c7",
      bgColor: "#ffffff",
      frameStyle: "badge",
      ctaText: "TOUCHLESS DIGITAL CHECK-IN",
    },
    locationTag: "Waiting Lounge Table Stands",
  },
  {
    id: "qr-7",
    clinicId: "clinic-in-01",
    type: "referral",
    title: "Patient Referral & Loyalty QR",
    subtitle: "Refer a friend, get ₹1,000 / $50 credit on your next dental visit",
    targetUrl: "/portal/clinic-in-01/hub#referral",
    scansCount: 290,
    conversionsCount: 94,
    revenueGenerated: 280000,
    customStyles: {
      fgColor: "#d97706",
      bgColor: "#ffffff",
      frameStyle: "callout",
      ctaText: "SHARE & EARN SMILE REWARDS",
    },
    locationTag: "Printed on Discharge Folders",
  },
  {
    id: "qr-8",
    clinicId: "clinic-in-01",
    type: "treatment_plan",
    title: "Interactive Treatment Plan QR",
    subtitle: "Personalized breakdown with 3D videos, costs & EMI options",
    targetUrl: "/portal/clinic-in-01/hub#treatment-plan",
    scansCount: 380,
    conversionsCount: 215,
    revenueGenerated: 920000,
    customStyles: {
      fgColor: "#7c3aed",
      bgColor: "#ffffff",
      frameStyle: "badge",
      ctaText: "VIEW YOUR TREATMENT ESTIMATE & EMI",
    },
    locationTag: "Treatment Estimate Printout",
  },
  {
    id: "qr-9",
    clinicId: "clinic-in-01",
    type: "emergency",
    title: "24x7 Dental Emergency Triage QR",
    subtitle: "Severe tooth pain, trauma, or swelling? Instant triage with on-call doctor",
    targetUrl: "/portal/clinic-in-01/emergency",
    scansCount: 210,
    conversionsCount: 88,
    revenueGenerated: 165000,
    customStyles: {
      fgColor: "#dc2626",
      bgColor: "#ffffff",
      frameStyle: "poster",
      ctaText: "EMERGENCY DENTAL CARE - SCAN NOW",
    },
    locationTag: "Clinic Glass Door (after hours)",
  },
  {
    id: "qr-10",
    clinicId: "clinic-in-01",
    type: "doctor",
    title: "Doctor Profile & Credentials QR",
    subtitle: "Meet Dr. Rajesh Sharma - MDS, Prosthodontist, 16+ Years Experience",
    targetUrl: "/portal/clinic-in-01/hub#doctors",
    scansCount: 340,
    conversionsCount: 120,
    revenueGenerated: 190000,
    customStyles: {
      fgColor: "#0f766e",
      bgColor: "#ffffff",
      frameStyle: "badge",
      ctaText: "MEET YOUR DENTIST",
    },
    locationTag: "Consultation Room Desk",
  },
  {
    id: "qr-11",
    clinicId: "clinic-in-01",
    type: "chair",
    title: "Operatory Chairside Companion QR",
    subtitle: "While in chair: home care instructions, post-op guides, instant checkout",
    targetUrl: "/portal/clinic-in-01/hub#chair",
    scansCount: 760,
    conversionsCount: 410,
    revenueGenerated: 450000,
    customStyles: {
      fgColor: "#0284c7",
      bgColor: "#ffffff",
      frameStyle: "simple",
      ctaText: "CHAIRSIDE PATIENT RESOURCES",
    },
    locationTag: "Mounted beside Dental Chair 1, 2, 3",
  },
];

export const initialKnowledgeDocs: KnowledgeDocument[] = [
  {
    id: "doc-k-1",
    clinicId: "clinic-in-01",
    title: "Dental Implant Surgical Protocol & Warranty Guidelines.pdf",
    fileType: "pdf",
    fileSize: "4.2 MB",
    chunksCount: 38,
    vectorStatus: "indexed",
    tags: ["Implants", "Titanium", "Warranty", "Post-Op"],
    lastUpdated: "2024-03-10",
    snippet:
      "All Straumann and Nobel Biocare implants placed at Apex Dental Studio come with a lifetime structural manufacturer warranty. Patients must maintain biannual clinical hygiene checks.",
  },
  {
    id: "doc-k-2",
    clinicId: "clinic-in-01",
    title: "Invisalign Clear Aligner Wear Schedule & FAQ.docx",
    fileType: "docx",
    fileSize: "1.8 MB",
    chunksCount: 24,
    vectorStatus: "indexed",
    tags: ["Invisalign", "Aligners", "Care", "Attachments"],
    lastUpdated: "2024-03-12",
    snippet:
      "Aligners must be worn 20 to 22 hours per day. Only remove for eating and brushing. Switch to next tray every 7 to 10 days as programmed in the ClinCheck software.",
  },
  {
    id: "doc-k-3",
    clinicId: "clinic-in-01",
    title: "Post-Extraction & Root Canal Home Care Instructions.pdf",
    fileType: "pdf",
    fileSize: "2.1 MB",
    chunksCount: 16,
    vectorStatus: "indexed",
    tags: ["Post-Op", "Emergency", "Bleeding", "Medication"],
    lastUpdated: "2024-03-15",
    snippet:
      "Keep cotton gauze firmly in place for 45 minutes. Avoid spitting, drinking through a straw, or vigorous rinsing for the first 24 hours to prevent dry socket.",
  },
  {
    id: "doc-k-4",
    clinicId: "clinic-in-01",
    title: "Clinic Fee Schedule & Zero-Percent EMI Packages.pdf",
    fileType: "pdf",
    fileSize: "850 KB",
    chunksCount: 12,
    vectorStatus: "indexed",
    tags: ["Pricing", "EMI", "Bajaj Finserv", "Credit Cards"],
    lastUpdated: "2024-03-20",
    snippet:
      "0% interest EMI available on 3, 6, and 9 month plans for treatments above ₹25,000 via Bajaj Finserv, HDFC, and ICICI credit cards with instant KYC.",
  },
];

export const initialWorkflows: WorkflowAutomation[] = [
  {
    id: "wf-1",
    clinicId: "clinic-in-01",
    name: "No-Show Prevention 3-Step WhatsApp Engine",
    category: "No-Show",
    trigger: "Appointment Scheduled",
    condition: "Status = Scheduled or Pending",
    action: "Send 48h, 24h & 2h WhatsApp interactive reminder cards with Confirm/Reschedule buttons",
    isActive: true,
    runsCount: 384,
    conversionRate: 94.6,
  },
  {
    id: "wf-2",
    clinicId: "clinic-in-01",
    name: "AI 2-Tier Google Review Funnel",
    category: "Review",
    trigger: "Treatment Marked Completed",
    condition: "2 Hours Post Checkout",
    action: "Send WhatsApp rating prompt: If score >= 8 -> direct Google 5-star link. If score <= 7 -> private clinic manager escalation ticket.",
    isActive: true,
    runsCount: 420,
    conversionRate: 72.8,
  },
  {
    id: "wf-3",
    clinicId: "clinic-in-01",
    name: "6-Month Preventive Hygiene Recall Sequence",
    category: "Recall",
    trigger: "175 Days Post Last Scaling/Cleaning",
    condition: "No upcoming appointment booked",
    action: "WhatsApp personalized reminder with Dr. recommendation + direct 1-click slot selector",
    isActive: true,
    runsCount: 650,
    conversionRate: 64.2,
  },
  {
    id: "wf-4",
    clinicId: "clinic-in-01",
    name: "High-Value Implant & Aligner Follow-up Journey",
    category: "Patient Journey",
    trigger: "Treatment Proposed (Value > ₹30,000)",
    condition: "Status = Treatment Proposed for > 48h",
    action: "AI Treatment Coordinator sends 3D simulation video, patient testimonial, and flexible EMI breakdown",
    isActive: true,
    runsCount: 142,
    conversionRate: 58.4,
  },
  {
    id: "wf-5",
    clinicId: "clinic-in-01",
    name: "Automated Outstanding Payment & Advance Deposit Reminder",
    category: "Billing",
    trigger: "Pending Balance > ₹5,000",
    condition: "Unpaid for 3 days post-visit",
    action: "Dispatches friendly WhatsApp reminder with UPI / Stripe payment link and itemized GST receipt preview",
    isActive: true,
    runsCount: 95,
    conversionRate: 88.0,
  },
];

export const initialReviews: ReviewFeedback[] = [
  {
    id: "rev-1",
    clinicId: "clinic-in-01",
    patientName: "Meera Singhania",
    phone: "+91 98203 99881",
    score: 10,
    feedbackText: "Dr. Rajesh and the staff made my implant surgery completely painless! The WhatsApp updates were so reassuring.",
    destination: "google_review",
    status: "Review Published",
    createdAt: "2024-03-24T17:20:00Z",
  },
  {
    id: "rev-2",
    clinicId: "clinic-in-01",
    patientName: "Kunal Mehra",
    phone: "+91 98190 22334",
    score: 10,
    feedbackText: "Incredible clinic! Scanned the QR at the door and was checked in without touching a pen. 5 stars!",
    destination: "google_review",
    status: "Review Published",
    createdAt: "2024-03-23T12:40:00Z",
  },
  {
    id: "rev-3",
    clinicId: "clinic-in-01",
    patientName: "Devendra Patil",
    phone: "+91 97020 55667",
    score: 6,
    feedbackText: "Doctor was excellent, but had to wait 20 minutes past my appointment time because of a previous emergency case.",
    destination: "internal_ticket",
    status: "Ticket In Review",
    createdAt: "2024-03-22T19:10:00Z",
  },
];

export const initialPayments: PaymentTransaction[] = [
  {
    id: "pay-1",
    clinicId: "clinic-in-01",
    patientName: "Pooja Deshmukh",
    treatmentName: "Invisalign Clear Aligners (Advance)",
    amount: 50000,
    currency: "INR",
    method: "UPI",
    status: "Completed",
    invoiceNumber: "INV-2024-0418",
    gstNumber: "27AABCA1234F1Z8",
    createdAt: "2024-03-24T18:02:00Z",
  },
  {
    id: "pay-2",
    clinicId: "clinic-in-01",
    patientName: "Amitabh Banerjee",
    treatmentName: "Rotary Root Canal Therapy",
    amount: 6500,
    currency: "INR",
    method: "Razorpay",
    status: "Completed",
    invoiceNumber: "INV-2024-0417",
    gstNumber: "27AABCA1234F1Z8",
    createdAt: "2024-03-21T12:00:00Z",
  },
  {
    id: "pay-3",
    clinicId: "clinic-in-01",
    patientName: "Rohit Malhotra",
    treatmentName: "CBCT 3D Scan & Surgical Guide",
    amount: 4500,
    currency: "INR",
    method: "PhonePe",
    status: "Completed",
    invoiceNumber: "INV-2024-0416",
    gstNumber: "27AABCA1234F1Z8",
    createdAt: "2024-03-20T11:45:00Z",
  },
];

export const initialEmergencyCases: EmergencyTriageCase[] = [
  {
    id: "em-1",
    clinicId: "clinic-in-01",
    patientName: "Gaurav Chawla",
    phone: "+91 98211 88443",
    symptoms: ["Severe Throbbing Tooth Pain", "Facial Swelling on Left Cheek", "Fever 100.4F"],
    urgencyScore: 9,
    urgencyLevel: "Critical",
    recommendedAction: "Acute periapical abscess suspected. Require immediate drainage and antibiotic coverage. Prioritized to Dr. Rajesh Sharma within 60 mins.",
    emergencySlotOffered: true,
    status: "Doctor Escalated",
    createdAt: "2024-03-25T08:30:00Z",
  },
  {
    id: "em-2",
    clinicId: "clinic-in-01",
    patientName: "Rhea Merchant",
    phone: "+91 98920 11002",
    symptoms: ["Broken Front Incisor", "Bleeding from Lip & Gum", "Sports Injury"],
    urgencyScore: 8,
    urgencyLevel: "High",
    recommendedAction: "Coronal fracture involving enamel-dentin. Preserve broken fragment in cold milk. Immediate composite bonding / crown prep required.",
    emergencySlotOffered: true,
    status: "Booked",
    createdAt: "2024-03-24T19:15:00Z",
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "log-1",
    clinicId: "clinic-in-01",
    userId: "user-admin-1",
    userName: "Dr. Rajesh Sharma",
    role: "Clinic Owner",
    action: "Updated Treatment Pricing: Implants",
    module: "Settings / Treatments",
    ipAddress: "115.112.44.18",
    device: "MacBook Pro / Chrome 122",
    timestamp: "2024-03-25T10:14:00Z",
    details: "Adjusted Zirconia Implant base fee from ₹35,000 to ₹38,000",
  },
  {
    id: "log-2",
    clinicId: "clinic-in-01",
    userId: "ai-worker-aria",
    userName: "Aria (AI Receptionist)",
    role: "AI Employee",
    action: "Booked Appointment via WhatsApp",
    module: "Appointments",
    ipAddress: "34.120.55.90 (GCP Cloud Run)",
    device: "Vertex AI Worker Node",
    timestamp: "2024-03-25T09:42:00Z",
    details: "Slot allocated for Sunita Kapoor with Dr. Ananya Sen",
  },
  {
    id: "log-3",
    clinicId: "clinic-in-01",
    userId: "user-frontdesk-1",
    userName: "Kavita Rao",
    role: "Front Desk",
    action: "Printed Starter Kit Posters",
    module: "Dental Growth Starter Kit",
    ipAddress: "115.112.44.18",
    device: "Windows 11 / Edge",
    timestamp: "2024-03-24T16:00:00Z",
    details: "Exported Print-Ready PDF posters for Universal QR and Review QR",
  },
];

export const initialQuickWinStats: QuickWinStats = {
  leadsGenerated: 142,
  whatsappConversations: 864,
  appointmentsBooked: 96,
  googleReviewsCollected: 48,
  paymentsCollected: 384000, // INR
  revenueInfluenced: 890000,
  aiConversationsResolved: 792,
  roiMultiplier: 11.4,
  hoursSaved: 68.5,
};
